#!/bin/sh

# Check the current branch
BRANCH_NAME=$(git symbolic-ref --short HEAD)

if [ "$BRANCH_NAME" = "main" ]; then
  echo "Pushing commits directly to the 'main' branch is not allowed!"
  exit 1
fi
